### ISSUE TITLE
[SUGGESTION] Auto-correct

### ISSUE THREAD

**Issue by rodrigoricky** [Ashwin-op/Google-Clone#4]
Add a auto-correct like google.

**Comment by Ashwin-op** [comment]
Hi @rodrigoricky, I did this mainly as a UI project. Feel free to create a PR if you implement it :)

**Comment by rodrigoricky** [comment]
Alr, and last thing where can I get the API key of custom search, can I have a link?

**Comment by Ashwin-op** [comment]
Check it out at [Custom Search JSON API](https://developers.google.com/custom-search/v1/overview)
